# At start, I wanted to makes the insert functions in the featuring files, but since we'll have 2 tables creates (the features one
# with one row for one link/attachment and the normalize one with one row with mean and sum of links/attachments features)
from .mail_features import (
    is_date_coherent,
    is_time_coherent,
    is_mail_extension_suspect,
    is_reply_to_suspect,
    is_spf_result_unapplicable,
    is_spf_result_suspect,
    is_dkim_result_unapplicable,
    is_dkim_result_suspect,
    count_spam_words_in_mail,
    ratio_spam_words_in_mail,
    number_of_words_content,
    is_XMailer_result_unapplicable,
    is_XMailer_result_suspect,
    is_display_name_suspect,
    is_spam,
)
from .link_features import (
    is_link_domain_age_unusable,
    is_link_domain_age_suspect,
    is_redirect_link_unusable,
    is_redirect_link_suspect,
    is_link_http,
    is_link_an_ipaddress,
    is_domain_name_suspect,
    is_site_extension_suspect,
)
from .attachment_features import (
    is_attachement_executable,
    is_double_extensions,
    is_no_extension,
    is_extension_suspect,
    is_file_empty,
    is_file_size_suspect,
    is_magic_number_suspect,
)

from .constants import spamwords_set


__all__ = [
    "is_date_coherent",
    "is_time_coherent",
    "is_mail_extension_suspect",
    "is_reply_to_suspect",
    "is_spf_result_unapplicable",
    "is_spf_result_suspect",
    "is_dkim_result_unapplicable",
    "is_dkim_result_suspect",
    "count_spam_words_in_mail",
    "ratio_spam_words_in_mail",
    "number_of_words_content",
    "is_XMailer_result_unapplicable",
    "is_XMailer_result_suspect",
    "is_display_name_suspect",
    "is_spam",
    "is_link_domain_age_unusable",
    "is_link_domain_age_suspect",
    "is_redirect_link_unusable",
    "is_redirect_link_suspect",
    "is_link_http",
    "is_link_an_ipaddress",
    "is_domain_name_suspect",
    "is_site_extension_suspect",
    "is_attachement_executable",
    "is_double_extensions",
    "is_no_extension",
    "is_extension_suspect",
    "is_file_empty",
    "is_file_size_suspect",
    "is_magic_number_suspect",
    "spamwords_set",
]
