# BE AWARE THAT ALL THE FUNCTIONS RETURN A NUMBER BETWEEN O AND 1, easy for the model and for the sum/mean for links/attacments per mails
from .constants import (
    safe_file_extensions,
    executable_file_extensions,
    common_file_extensions,
    suspect_file_extensions,
    file_extensions,
)

# Actually, theses features are nearly useless since the training dataset has 4k attachments for 36k mails, and like 0 attachments attacks
# but I assume that it could be useful if u use a dataset with lot of attacks per attachments and train the model on it

# some functions use a json file in data directory (feature_engineering/data) theses files are generated by AI
# (lack of datas in net and time) and are exhaustive so don't take theses functions as a hyper relevant. you can go in data
# folder and change the json if you want or if you have usefuls datas

# You can change the returns score, I choosed them arbitrarly and they can be bad, bu I think it's mostly OK since the case are separated


def is_attachement_executable(
    extension,
):  # this is like very very important, nobody send an exe file
    ext = "." + extension
    if ext in executable_file_extensions:
        return 1
    return 0


def is_double_extensions(
    filename,
):  # very important too cause it's literally a try to hide the real extension
    parts = filename.split(".")
    if len(parts) > 2:
        return 1
    return 0


def is_no_extension(extension):  # weird but not all times a threat
    if extension == "Unknown":
        return 1
    return 0


def is_extension_suspect(extension, filename):

    if is_attachement_executable(extension) or is_double_extensions(filename):
        return 1
    if is_no_extension(extension):
        return 1
    ext = "." + extension
    if ext in suspect_file_extensions:
        return 1
    if ext in common_file_extensions:
        return 0.2
    if ext in safe_file_extensions:
        return 0
    return 0.5


def is_file_empty(
    file_size,
):  # phantom files are really weird, it can be a good indicators
    if file_size == 0:
        return 1
    return 0


def is_file_size_suspect(
    file_size, extension
):  # it's exhaustive and habitually detect phantom files too, maybe useless but canno't confirm with so little amount of attachments
    if is_file_empty(file_size):
        return 1
    ext = "." + extension
    if ext in file_extensions:
        if (file_size) < file_extensions[ext]["size_range"]["min_bytes"] or (
            file_size
        ) > file_extensions[ext]["size_range"]["max_bytes"]:
            return 1
    return 0


def is_magic_number_suspect(
    extension, magic_number
):  # really really important but one more time we don't have attachments attacks
    ext = "." + extension
    if extension == "Unknown":
        return 1
    if ext not in file_extensions:
        return 0.5

    json_magic = file_extensions[ext]["magic"]

    if json_magic is None:
        if magic_number == "Unknown":
            return 0
        return 1
    if magic_number == "Unknown":
        return 1

    magic_clean = magic_number.replace(" ", "").upper()
    patterns = json_magic if isinstance(json_magic, list) else [json_magic]

    for pattern_raw in patterns:
        chunks = pattern_raw.replace(" ", "").upper()
        match = True
        for i in range(0, len(chunks), 2):
            pat_byte = chunks[i : i + 2]
            mag_byte = magic_clean[i : i + 2]
            if (
                pat_byte == "??"
            ):  # some magic number in json file have ?? in it, to say that some bytes are changing depending on the file
                continue
            if pat_byte != mag_byte:
                match = False
                break

        if match:
            return 0

    return 1
