# BE AWARE THAT ALL THE FUNCTIONS RETURN A NUMBER BETWEEN O AND 1, easy for the model and for the sum/mean for links/attacments per mails
import os
from .utils import (
    convert_date_to_obj,
    is_ipadress,
    get_best_jaro_score,
    string_substitutions_spoof,
)
from urllib.parse import urlparse
from .constants import (
    safe_domains,
    common_domains,
    suspect_domains,
    safe_site_extensions,
    common_sites_extensions,
    suspect_sites_extensions,
)
from .utils import Detector



# some functions use a json file in data directory (feature_engineering/data) theses files are generated by AI
# (lack of datas in net and time) and are exhaustive so don't take theses functions as a hyper relevant. you can go in data
# folder and change the json if you want or if you have usefuls datas


# the dataset training have some terrible distribution of dates (lot of mail from 2000's and lot of 2020's)
# so we have many links that are dead links and this not means that the sites are suspects (it's annoying
# cause peoples will surely use it on recent mails so a dead links is weird, but not in the training dataset)

# You can change the returns score, I choosed them arbitrarly and they can be bad, bu I think it's mostly OK since the case are separated


# the ... unsuable functions permit to say to the model if he have to consider or not the feature below them
def is_link_domain_age_unusable(domain_creation_date):
    if (
        domain_creation_date == "Rate Limited"
        or domain_creation_date == "Invalid"
        or domain_creation_date == "No Info"
    ):
        return 1
    return 0


def is_link_domain_age_suspect(
    domain_creation_date, mail_date
):  # Really useful, cover all cases of the parsing domain age but we have a lot of unusable links
    # since we have a lot of rate limited(even with the rdap concurrency low)
    if is_link_domain_age_unusable(domain_creation_date):
        return 0.1
    if domain_creation_date == "Unknown":
        return 0.9
    if domain_creation_date == "Protected":
        return 0.25
    if domain_creation_date == "Timeout":
        return 0.75
    if domain_creation_date == "Forbidden":
        return 1
    if domain_creation_date == "Error":
        return 0.7
    if isinstance(convert_date_to_obj(mail_date), str):
        return 0.5
    if (
        convert_date_to_obj(mail_date) - convert_date_to_obj(domain_creation_date)
    ).days <= 30:
        return 1
    if (
        convert_date_to_obj(mail_date) - convert_date_to_obj(domain_creation_date)
    ).days <= 90:
        return 0.8
    return 0


def is_redirect_link_unusable(redirect_link):
    if redirect_link == "Error":
        return 1
    return 0


def is_redirect_link_suspect(redirect_link, domain_creation_date, mail_date):
    if is_redirect_link_unusable(redirect_link):
        return 0.25
    if redirect_link == "No Redirect":
        return 0
    if redirect_link == "SSL Error" or redirect_link == "Redirect Loop":
        return 1
    if (
        redirect_link == "Not Found"
        or redirect_link == "Connection Error"
        or redirect_link == "Timeout"
    ) and is_link_domain_age_suspect(domain_creation_date, mail_date) >= 0.75:
        return 1
    return 0.3


def is_link_http(url):  # really good spam indicators, http is really suspect
    if url.startswith("http://"):
        return 1
    if url.startswith("https://"):
        return 0
    return 0.8


def is_link_an_ipaddress(url):  # same it's really suspect to hae an url with ip adress
    try:
        host = urlparse(url).hostname
        if host is None:
            return 0.5
        if is_ipadress(host):
            return 1
        return 0
    except ValueError:
        return 0.5


def is_domain_name_suspect(domain_name):
    if domain_name == "Unknown":
        return 1
    domain_name.lower().strip()
    if domain_name in safe_domains:
        return 0
    if domain_name in common_domains:
        return 0.1
    if domain_name in suspect_domains:
        return 1
    try:
        if Detector.is_gibberish(
            domain_name
        ):  # is_gibberish can return an error if the string is too short, but it's not a problem since a too short domain name could be suspec
            return 1
    except:
        return 1  # too short domain name, weird
    return 0.25


def is_site_extension_suspect(url):  # useful too
    url = url.strip("[]()\"' ")
    parts = url.split(".")
    if len(parts) < 2:
        return 1
    ext = "." + parts[-1]
    if ext in safe_site_extensions:
        return 0
    if ext in common_sites_extensions:
        return 0.1
    if ext in suspect_sites_extensions:
        return 1
    if (
        get_best_jaro_score(string_substitutions_spoof(ext), safe_site_extensions)
        >= 0.88
    ):  # 0.89 is the jaro score of a 3 letters string with 1 substitution
        return 1
    if (
        get_best_jaro_score(string_substitutions_spoof(ext), common_sites_extensions)
        >= 0.88
    ):
        return 1
    return 0.5
