# BE AWARE THAT ALL THE FUNCTIONS RETURN A NUMBER BETWEEN O AND 1, easy for the model and for the sum/mean for links/attacments per mails
from .utils import (
    convert_date_to_obj,
    convert_time_to_obj,
    string_substitutions_spoof,
    get_best_jaro_score,
)
import os
from datetime import datetime
from .constants import (
    spamwords_set,
    safe_mail_extensions,
    common_mail_extensions,
    suspect_mail_extensions,
    common_XMailer,
    suspect_Xmailer,
    public_identities,
)
from .utils import Detector


# some functions use a json file in data directory (feature_engineering/data) theses files are generated by AI
# (lack of datas in net and time) and are exhaustive so don't take theses functions as a hyper relevant. you can go in data
# folder and change the json if you want or if you have usefuls datas

# You can change the returns score, I choosed them arbitrarly and they can be bad, bu I think it's mostly OK since the case are separated


def is_date_coherent(
    mail_date,
):  # useful since i had some mail from the future and some mails from the Middles Ages (maybe a parsing problem but parsing
    # but I covered nearly all case (horrible time) for parsing date so if it's in bad format it's weird)
    mail_date = convert_date_to_obj(mail_date)
    if mail_date == "Unknown" or mail_date == "Format Problem":
        return 0.75
    if mail_date.year < 1971:  # Email creation date
        return 1
    if mail_date > datetime.now():  # Email sent in the future ??? threat
        return 1
    return 0


def is_time_coherent(
    mail_time,
):  # Not useful, thought it was a good indicators, but receive a mail at 1AM can just means the mail is from another country
    mail_time = convert_time_to_obj(mail_time)
    if mail_time == "Unknown" or mail_time == "Format Problem":
        return 0.75
    if (
        mail_time.hour > 0 and mail_time.hour < 5
    ):  # i thought night hours can be suspects but not really
        return 1
    return 0


def is_mail_extension_suspect(
    sender_mail,
):  # useful when the sender is a public identity but normal sender don't have extension in their name
    if sender_mail == "Unknown":  # Sender without name ? suspect
        return 1
    ext = sender_mail.split(".")[-1].lower()  # classification with json file
    if ext in safe_mail_extensions:
        return 0
    if ext in common_mail_extensions:
        return 0.25
    if ext in suspect_mail_extensions:
        return 1
    return 0.3


def is_reply_to_suspect(
    sender_mail, reply_to_mail
):  # like above, useful for public identities, but normal sender don't have reply to
    if sender_mail == "Unknown":
        return 1
    if (
        reply_to_mail == "Unknown"
    ):  # personal account does not have a reply to specified
        return 0.3
    if sender_mail != reply_to_mail:
        return 0.75
    return 0


def is_spf_result_unapplicable(
    mail_date,
):  # since my dataset have old mails and SPF DKIM were not always a standard,
    # I decided to verify if the SPF/DKIM are logic to use depending of the dates
    if mail_date == "Unknown" or convert_date_to_obj(mail_date) == "Format Problem":
        return 1
    if (
        convert_date_to_obj(mail_date)
    ).year < 2014:  # Standardization of the SPF protection, cannot interpret missing values before this date
        return 1
    return 0


def is_spf_result_suspect(
    SPF_result,
):  # for recent mail, REALLY USEFUL, SPF is a standard, not having it is weird, and fail spf is absolute indicator of spam mail
    if SPF_result == "Pass (Legitimate)":
        return 0
    if SPF_result == "Fail (Threat)" or SPF_result == "Missing":
        return 1
    if (
        SPF_result == "PermError (Config Error)"
        or SPF_result == "TempError (Temporary Issue)"
        or SPF_result == "None (No Info)"
    ):
        return 0.75
    if SPF_result == "SoftFail (Suspect)":
        return 0.5
    return 0


def is_dkim_result_unapplicable(
    mail_date,
):  # same as above, verify if DKIM usable with the date of the mail
    if convert_date_to_obj(mail_date) == "Format Problem" or mail_date == "Unknown":
        return 1
    if (
        convert_date_to_obj(mail_date)
    ).year < 2012:  # Standardization of the DKIM protection, cannot interpret missing values before this date
        return 1
    return 0


def is_dkim_result_suspect(
    DKIM_result,
):  # like above, aboslute indicator of threat, and standard so not having it is suspect too
    if DKIM_result == "Pass (Legitimate)":
        return 0
    if (
        DKIM_result == "Fail (Modified or Forged))"
        or DKIM_result == "Missing"
        or DKIM_result == "Unknown"
    ):
        return 1
    if DKIM_result == "None (Not Signed)":
        return 0.75
    if DKIM_result == "Present (Not Verified)":
        return 0.5
    return 0


def count_spam_words_in_mail(
    subject, content
):  # works very well, this spamwords json is not generated and return a lot of spamming words as I saw in features db
    score = 0
    words_email = subject + " " + content

    clean_words = (
        words_email.lower()
        .replace("[lien]", " ")
        .replace("[image]", " ")
        .strip()
        .split(" ")
    )

    for word in clean_words:
        if word in spamwords_set:
            score += 1
    return score


def ratio_spam_words_in_mail(
    subject, content
):  # ratio and count are generally useful to have together cause lot of words in a long mail can be logic
    words_email = subject + " " + content

    clean_words = (
        words_email.lower()
        .replace("[lien]", " ")
        .replace("[image]", " ")
        .strip()
        .split(" ")
    )

    if not clean_words:
        return 0

    return count_spam_words_in_mail(subject, content) / len(clean_words)


def number_of_words_content(content):  # idk if it's useful, but can be so I made it
    if content == "[No content]":
        return 0
    words_content = (
        content.lower()
        .replace("[lien]", " ")
        .replace("[image]", " ")
        .strip()
        .split(" ")
    )
    return len(words_content)


def is_XMailer_result_unapplicable(
    Xmail_result,
):  # XMailer are generally missing (idk if it's a parsing problem) so I verify if it's usable
    if Xmail_result == "Missing":
        return 1
    return 0


def is_XMailer_result_suspect(Xmail_result):
    if Xmail_result == "Missing":
        return 0.25

    Xmail_result = Xmail_result.lower().strip()

    if any(Xmailer in Xmail_result for Xmailer in suspect_Xmailer):
        return 1
    if any(Xmailer in Xmail_result for Xmailer in common_XMailer):
        return 0.1
    try:
        if Detector.is_gibberish(
            Xmail_result
        ):  # some of Xmailers are just random strings so it's detect very well this problem
            return 1
    except (
        ValueError
    ):  # and if it's too short it's weird too, usually we have the name of the program sender, and the version so it can't be short
        return 1
    return 0.5


def is_display_name_suspect(
    display_name,
):  # useful for public identities but not relevant for personal mails
    if (
        display_name == "Unknown"
    ):  # some mails in the database have no sender, absolutely weird (generally the mails are empty)
        return 1
    display_name = display_name.lower().strip()
    if display_name in public_identities:
        return 0
    if (
        get_best_jaro_score(string_substitutions_spoof(display_name), public_identities)
        > 0.8
    ):
        return 1
    return 0.25


def is_spam(label):  # ONLY FOR TRAINING
    if label == "spam":
        return 1
    if label == "ham":
        return 0
    return None


# since Here, I added some features since the model wasn't accurate enough in my opinion.
def count_received_headers(msg):
    return len(msg.get_all("Received") or [])


def count_duplicate_from_headers(msg):
    count = len(msg.get_all("From") or [])
    return max(count - 1, 0)


def count_duplicate_subject_headers(msg):
    count = len(msg.get_all("Subject") or [])
    return max(count - 1, 0)


def count_duplicate_content_type_headers(msg):
    count = len(msg.get_all("Content-Type") or [])
    return max(count - 1, 0)


def count_duplicate_message_id_headers(msg):
    count = len(msg.get_all("Message-ID") or [])
    return max(count - 1, 0)


def has_message_id(msg):
    return 0 if msg.get("Message-ID") else 1


def count_x_headers(msg):
    return sum(1 for key in msg.keys() if key.lower().startswith("x-"))
